package SQL;

public class SQLCode {

    //Names of the required Tables
    public static String[] getReqTables(){
        return new String[]{"inserate", "Privat_Acc", "Pro_Acc", "ZA_Auto", "ZA_LKW", "model_auto", "model_lkw"};
    }

    //SQL to create needed Tables
    public static String[] getCreateCode(){
        String create_privat = "CREATE TABLE Privat_Acc (" +
                "AccID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Vorname VARCHAR(255) NOT NULL," +
                "Nachname VARCHAR(255) NOT NULL," +
                "Mail VARCHAR(255) NOT NULL," +
                "Passwort VARCHAR(255) NOT NULL," +
                "PRIMARY KEY(AccID)" +
                ");";

        String create_pro = "CREATE TABLE Pro_Acc (" +
                "AccID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Firmenname VARCHAR(255) NOT NULL," +
                "Oeffnungszeiten VARCHAR(255) NOT NULL," +
                "Mail VARCHAR(255) NOT NULL," +
                "Passwort VARCHAR(255) NOT NULL," +
                "PRIMARY KEY(AccID)" +
                ");";

        String create_zusatz_auto = "CREATE TABLE ZA_Auto (" +
                "ZaID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Sportpaket BOOLEAN NOT NULL," +
                "PRIMARY KEY(ZaID)" +
                ");";

        String init_zusatz_auto_1 = "INSERT INTO ZA_Auto (Sportpaket) VALUES (true);";
        String init_zusatz_auto_2 = "INSERT INTO ZA_Auto (Sportpaket) VALUES (false);";

        String create_zusatz_lkw = "CREATE TABLE ZA_LKW (" +
                "ZaID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Hydraulik BOOLEAN NOT NULL," +
                "PRIMARY KEY(ZaID)" +
                ");";

        String init_zusatz_lkw_1 = "INSERT INTO ZA_LKW (Hydraulik) VALUES (true);";
        String init_zusatz_lkw_2 = "INSERT INTO ZA_LKW (Hydraulik) VALUES (false);";

        String create_mod_auto = "CREATE TABLE model_auto (" +
                "ModID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Marke VARCHAR(255) NOT NULL," +
                "Modell VARCHAR(255) NOT NULL," +
                "Leistung INTEGER NOT NULL," +
                "Gewicht INTEGER NOT NULL," +
                "Variante VARCHAR(255) NOT NULL," +
                "PRIMARY KEY(ModID)" +
                ");";

        String create_mod_lkw = "CREATE TABLE model_lkw (" +
                "ModID INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "Marke VARCHAR(255) NOT NULL," +
                "Modell VARCHAR(255) NOT NULL," +
                "Leistung INTEGER NOT NULL," +
                "Gewicht INTEGER NOT NULL," +
                "Zuladung INTEGER NOT NULL," +
                "Zuglast FLOAT NOT NULL," +
                "PRIMARY KEY(ModID)" +
                ");";

        String create_ins = "CREATE TABLE inserate (" +
                "InsID INTEGER GENERATED BY DEFAULT AS IDENTITY," +

                "AutoID INTEGER NULL," +
                "LkwID INTEGER NULL," +
                "PrivAccID INTEGER NULL," +
                "ProAccID INTEGER NULL," +

                "Erstzulassung VARCHAR(255) NOT NULL," +
                "Einstelldatum VARCHAR(255) NOT NULL," +
                "Odometer INTEGER NOT NULL," +
                "Preis INTEGER NOT NULL," + //real = 6 decimal digits

                "ZusatzAutoID INTEGER NULL," +
                "ZusatzLkwID INTEGER NULL," +

                "PRIMARY KEY(InsID)," +

                "CONSTRAINT FK_Auto FOREIGN KEY(AutoID) REFERENCES model_auto(ModID) ON DELETE SET NULL," +
                "CONSTRAINT FK_Lkw FOREIGN KEY(LkwID) REFERENCES model_lkw(ModID) ON DELETE SET NULL," +
                "CONSTRAINT FK_PrivAcc FOREIGN KEY(PrivAccID) REFERENCES Privat_Acc(AccID) ON DELETE CASCADE," +
                "CONSTRAINT FK_ProAcc FOREIGN KEY(ProAccID) REFERENCES Pro_Acc(AccID) ON DELETE CASCADE," +
                "CONSTRAINT FK_ZA_Auto FOREIGN KEY(ZusatzAutoID) REFERENCES ZA_AUTO(ZaID) ON DELETE SET NULL," +
                "CONSTRAINT FK_ZA_Lkw FOREIGN KEY(ZusatzLkwID) REFERENCES ZA_LKW(ZaID) ON DELETE SET NULL," +

                "CONSTRAINT CK_Auto_Lkw CHECK (" + //Only Key to Auto or Lkw set
                "CASE WHEN AutoID IS NULL THEN 0 ELSE 1 END +" +
                "CASE WHEN LkwID IS NULL THEN 0 ELSE 1 END = 1" +
                ")," +

                "CONSTRAINT CK_Acc CHECK (" + //Only Key to Privat Account or Pro Account set
                "CASE WHEN PrivAccID IS NULL THEN 0 ELSE 1 END +" +
                "CASE WHEN ProAccID IS NULL THEN 0 ELSE 1 END = 1" +
                ")," +

                "CONSTRAINT CK_ZA CHECK (" + //Only Key to Zusatzattribut-Auto or Zusatzattribut-LKW set
                "CASE WHEN ZusatzAutoID IS NULL THEN 0 ELSE 1 END +" +
                "CASE WHEN ZusatzLkwID IS NULL THEN 0 ELSE 1 END = 1" +
                ")" +
                ");";
        return new String[]{create_privat, create_pro, create_zusatz_auto, create_zusatz_lkw, init_zusatz_auto_1, init_zusatz_auto_2, init_zusatz_lkw_1, init_zusatz_lkw_2, create_mod_auto, create_mod_lkw, create_ins};
    }
}
